name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Compose Action
      uses: isbang/compose-action@v0.2.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
